### ISSUE TITLE
Set up issue / PR labels

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy_editor_prototypes#10]
Copy the standard from Bevy. Let me know if you want to do this and need permissions, and reach out if you need advice.

**Comment by alice-i-cecile** [comment]
This seems largely complete; closing. Feel free to add more freely!

**Comment by alice-i-cecile** [comment]
Actually, we still need all the `C-` labels, and to remove Github's initial labels.

**Comment by Loweredgames** [comment]
fix?

**Comment by alice-i-cecile** [comment]
Yeah this is done now :)
