### ISSUE TITLE
CI checks aren't being run in the merge queue correctly

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy_editor_prototypes#18]
See https://github.com/bevyengine/bevy_editor_prototypes/queue/main

This works fine on the main Bevy repo, so maybe there's a config problem. We can also just turn off the merge queue, although it is convenient.

**Comment by bjorn3** [comment]
Looks like the `merge_queue` trigger for the ci workflow is missing.

This repo: https://github.com/bevyengine/bevy_editor_prototypes/blob/eaea4191a8a47bb5dc2b24002c442e208a40ffd0/.github/workflows/ci.yaml#L4-L5
The main bevy repo: https://github.com/bevyengine/bevy/blob/612897becd415b7b982f58bd76deb719b42c9790/.github/workflows/ci.yml#L4

**Comment by janhohenheim** [comment]
Good catch, let me fix it real quick :)
