### ISSUE TITLE
CI doesn't like targeting Bevy's main branch

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy_editor_prototypes#31]
Git dependencies seem messed up. See https://github.com/bevyengine/bevy_editor_prototypes/actions/runs/10999742035/job/30540587660?pr=24, from #24.

Paging @BD103, @mockersf and @tim-blackbird, who may have ideas on how to fix this.

**Comment by BD103** [comment]
That looks like a simple 404 (not found) error code. It likely was just a spontaneous error, let me try re-running CI.

**Comment by BD103** [comment]
It was a small error in the manifest. [Comment](https://github.com/bevyengine/bevy_editor_prototypes/pull/24/files#r1771942439)
