### ISSUE TITLE
Refactor initial editor stages

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy_editor_prototypes#49]
https://discord.com/channels/691052431525675048/789987800014651412/1290117367606677564

 Yeah that makes some sense to me. Establishing the foundation of the editor and creating read-only versions of widgets for the component editor is a decent chunk of work for step 1. 

Step 2 could be the editing mvp. Basically adding edit capability to those widgets, add/remove entities/components, and being able to save scenes. Maybe throw in a transform gizmo because that’s something everyone is going to look for.

**Comment by alice-i-cecile** [comment]
Remember to update the milestones on this repo too :)

**Comment by MiniaczQ** [comment]
related #51
