### ISSUE TITLE
Upstream `bevy_basic_prefs`

### ISSUE THREAD

**Issue by NthTensor** [bevyengine/bevy_editor_prototypes#62]
Veridia has generously recommended we base our preferences system on their [`bevy_basic_prefs`](https://github.com/viridia/bevy_basic_prefs) crate.

This needs to be:
+ [ ] Copied into this repo as `bevy_prefs` or similar,
+ [ ] Updated to run on main
+ [ ] Ideally cleaned up and documented a bit, but that's not required.

**Comment by n1ght-hunter** [comment]
Im going to close this as I have rewritten bevy basic prefs and merged a decent portion of the code
