### ISSUE TITLE
Add basic CI

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy_editor_prototypes#9]
Clippy, rustfmt, cargo test, mdbook compiles without error etc.

Either steal from the Bevy / Bevy website repo, or roll something simple with cargo-cache

**Comment by janhohenheim** [comment]
I recommend the one from https://github.com/TheBevyFlock/bevy_quickstart, that one was really carefully steadily optimized :)

**Comment by alice-i-cecile** [comment]
Perfect, grab that. We can add typos and mdbook on top of that.
